### ISSUE TITLE
karen's build is failed on Windows.

### ISSUE THREAD

**Issue by saneyuki** [karen-irc/karen#240]
e.g.

```sh
$ gulp jslint
[20:37:45] Using gulpfile ~\src\karen\gulpfile.js
[20:37:45] Starting 'jslint'...
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: spawn ~\src\karen\node_modules\.bin\eslint ENOENT
    at exports._errnoException (util.js:846:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:177:32)
    at onErrorNT (internal/child_process.js:343:16)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:117:18)
    at node.js:946:3
```

**Comment by saneyuki** [comment]
This specifying tries to execute `~\src\karen\node_modules\.bin\eslint`, but there is only `eslint.cmd` on Windows.

We have 2 approach to resolve this.

- call bin file directly like `./node_modules/bar-foo/bin/bar-foo.js`
- create a wrapper like `function createBinPath(path) { return isWin ? bin + '.cmd' : bin  }`
